; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26429.4 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Tay\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
